name: Release – version + edge images
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag"
        required: true
  repository_dispatch:
    types: [trigger-docker-build]
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
  VERSION: ${{ github.event.inputs.version || github.event.client_payload.version || github.event.release.tag_name }}

jobs:
  release-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [streamystats-nextjs, streamystats-phoenix]
        include:
          - part: streamystats-nextjs
            folder: app
          - part: streamystats-phoenix
            folder: server

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push ${{ matrix.part }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.folder }}
          file: ./${{ matrix.folder }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:edge
