name: CI – docker build & push

on:
  push:
    branches: [master]

env:
  REGISTRY: docker.io
  IMAGE_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        part:
          - streamystats-v2-nextjs
          - streamystats-v2-job-server
          - streamystats-v2-migrate
        include:
          - part: streamystats-v2-nextjs
            folder: .
            dockerfile: apps/nextjs-app/Dockerfile
          - part: streamystats-v2-job-server
            folder: .
            dockerfile: apps/job-server/Dockerfile
          - part: streamystats-v2-migrate
            folder: .
            dockerfile: migration.Dockerfile

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push ${{ matrix.part }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.folder }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64

          # ---------- BuildKit optimisations ----------
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            COMMIT_SHA=${{ github.sha }}
            BUILD_TIME=${{ github.event.head_commit.timestamp }}
          cache-from: |
            type=registry,ref=${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:cache-deps
            type=registry,ref=${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:cache-build
            type=registry,ref=${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:cache-runtime
          cache-to: |
            type=registry,ref=${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:cache-deps,mode=max
            type=registry,ref=${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:cache-build,mode=max
            type=registry,ref=${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:cache-runtime,mode=max
          # --------------------------------------------

          push: true
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:latest
            ${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:${{ github.sha }}
