name: Release – version + edge images
on:
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  release-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [app, server]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ matrix.part }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.part }}
          file: ./${{ matrix.part }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAMESPACE }}/${{ matrix.part }}:edge
