name: Streamystats CI

on:
  pull_request:
    branches: # Trigger on PRs targeting any branch (like main)
      - main
  push:
    branches: # Trigger on pushes ONLY to the main branch
      - main

jobs:
  build_and_push:
    name: Build & Publish Docker Images
    # Run on pushes to main OR any pull request event, unless skipped
    if: (github.ref == 'refs/heads/main' || github.event_name == 'pull_request') && !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-22.04
    permissions: # Needed by metadata-action to get tags based on PRs
      contents: read
      pull-requests: read # Optional: If you want tags based on PR labels or milestones

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        # Only log in if we are actually pushing (main branch or PRs in this config)
        # If you decide NOT to push PR images, add an `if` here:
        # if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # --- Metadata for Next.js App ---
      - name: Docker meta for Next.js
        id: meta_nextjs # IMPORTANT: Give it an ID
        uses: docker/metadata-action@v5
        with:
          images: fredrikburmester/streamystats-nextjs
          tags: |
            # tag latest on main branch pushes
            type=edge,branch=main
            # tag commit sha on main branch pushes
            type=sha,prefix=,suffix=,event=push,branch=main
            # tag pr-<pr_number> on pull requests
            type=ref,event=pr

      # --- Metadata for Phoenix Server ---
      - name: Docker meta for Phoenix
        id: meta_phoenix # IMPORTANT: Give it an ID
        uses: docker/metadata-action@v5
        with:
          images: fredrikburmester/streamystats-phoenix
          tags: |
            # tag latest on main branch pushes
            type=edge,branch=main
            # tag commit sha on main branch pushes
            type=sha,prefix=,suffix=,event=push,branch=main
            # tag pr-<pr_number> on pull requests
            type=ref,event=pr

      # --- Build Next.js App ---
      - name: Build and push Next.js app
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64
          # Use tags and labels generated by the metadata action
          tags: ${{ steps.meta_nextjs.outputs.tags }}
          labels: ${{ steps.meta_nextjs.outputs.labels }}
          push: true # Push for both main and PRs
          cache-from: type=gha # Optional: Enable build cache
          cache-to: type=gha,mode=max # Optional: Enable build cache

      # --- Build Phoenix Server ---
      - name: Build and push Phoenix server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64,linux/arm64
          # Use tags and labels generated by the metadata action
          tags: ${{ steps.meta_phoenix.outputs.tags }}
          labels: ${{ steps.meta_phoenix.outputs.labels }}
          push: true # Push for both main and PRs
          cache-from: type=gha # Optional: Enable build cache
          cache-to: type=gha,mode=max # Optional: Enable build cache
