name: release-please
on:
  push:
    branches: [main]

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
          include-v-in-tag: true
          command: manifest-pr

      # Create a GitHub release when a version tag is created
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Create GitHub Release
        if: ${{ steps.release.outputs.release_created }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.release.outputs.tag_name }}
          name: Release ${{ steps.release.outputs.tag_name }}
          generateReleaseNotes: true

      # Trigger Docker build workflow
      - name: Trigger Docker build workflow
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-docker-build
          client-payload: '{"version": "${{ steps.release.outputs.tag_name }}"}'
